### PR TITLE
Forman 121 use keycloak and router

### PR DESCRIPTION
**Pull request by forman**
In this PR

* Using KeyCloak authentication and user management service running in the project's JASMIN cloud tenant. (#121)
* Using a new Cate WebAPI cloud service provider running in the project's JASMIN cloud tenant. 
* Using web page routing to for CateApps main pages:
  - `${origin}/`  - the login screen
  - `${origin}/hub`  - main page that runs with Cate's cloud service provider 
  - `${origin}/sa?serviceUrl=${serviceUrl}` - to run the app with a stand-alone server at `${serviceUrl}`

### CODE REVIEW

**Review by dzelge — CHANGES_REQUESTED** [review]
cate webapi service url should come from .env

**Review by dzelge — APPROVED** [review]

**Comment by AliceBalfanz** [comment]
When testing on ubuntu:
http://localhost:3000/hub

Firefox:
I can login and logout, however when I click on Account an Unhandled Rejection (TypeError) happens: accountWindow is null
image

Chrome: 
Account and Logout Button are not accessible at all. 

Furthermore, variable mapping does not work in both browsers:
image

**Comment by forman** [comment]
This happens on Firefox whenever I leave the page i.e. before login and logout and account management:

image

**Comment by pont-us** [comment]
Error message after clicking on "Cate Cloud Service", Ubuntu 20.04, Firefox 80.0.1. Only started appearing after a couple of cycles of login / logout testing, but now impossible to avoid. Not helped by allowing pop-ups for localhost as in Alicja's coment.

**Comment by forman** [comment]
> Chrome:
> Account and Logout Button are not accessible at all.

Found something: https://www.keycloak.org/docs/latest/securing_apps/#_modern_browsers

**Pull request merged**
